import {
  FIREBASEAPIKEY,
  FIREBASEAPPID,
  FIREBASEAUTHDOMAIN,
  FIREBASEDATABASEURL,
  FIREBASESTORAGEBUCKET,
  FIREBASEPROJECTID,
  MESSAGINGSENDERID
} from '../env'
export const firebaseConfig = {
  apiKey: FIREBASEAPIKEY,
  authDomain: FIREBASEAUTHDOMAIN,
  databaseURL: FIREBASEDATABASEURL,
  projectId: FIREBASEPROJECTID,
  storageBucket: FIREBASESTORAGEBUCKET,
  messagingSenderId: MESSAGINGSENDERID,
  appId: FIREBASEAPPID
}
