@hostname = localhost
@port = 3001
@baseurl = http://{{hostname}}:{{port}}/api
@contentType = application/json
@business_id = 5e17d52abefd53d9697375d5
### GET BUSINESSES

#  Can be formated as query like so: businesses/?page=1
GET {{baseurl}}/businesses/?page=10


### GET BUSINESS BY ID

GET {{baseurl}}/businesses/{{business_id}}

### POST BUSINESS

POST  {{baseurl}}/businesses
Content-Type: {{contentType}}

{
  "business":{
    "name": "New Cutzz",
    "address": {
      "address_line": "1234 Wallaby way",
      "zip_code": "123456",
      "city": "Union",
      "state": "NJ",
      "cc": "US"
    },
    "hours": [
      {
        "day": "Monday",        
        "open_time": "9:00 AM",
        "close_time": "5:00 PM"
      }
    ],
    "phone_number": "123-123-1234"
}
}


### PUT BUSINESS
PUT {{baseurl}}/businesses/1234/details
Content-Type: {{contentType}}

{
   "business":{
    "name": "New Cutzz",
    "address": {
      "address_line": "1234 Wallaby way",
      "zip_code": "123456",
      "city": "Union",
      "state": "NJ",
      "cc": "US"
    },
    "phone_number": "123-123-1234",
    "hours": [
      {
        "day": "Monday",        
        "open_time": "9:30 AM",
        "close_time": "5:00 PM"
      },
      {
        "day": "Tuesday",        
        "open_time": "9:30 AM",
        "close_time": "5:30 PM"
      },
      {
        "day": "Thursday",        
        "open_time": "9:00 AM",
        "close_time": "6:00 PM"
      }
    ]
}
}

### PUT BUSINESS ADD EMPLOYEES

PUT {{baseurl}}/businesses/{{business_id}}/employees
Content-Type: {{contentType}}

{
  "employees": [
      {
    "_id": "5e190adc92477d5902490532",
    "name": "Sage Rippin",
    "profile_img":
      "https://s3.amazonaws.com/uifaces/faces/twitter/adamnac/128.jpg",
    "email": "Bonnie83@yahoo.com",
    "business_id": "5e17d52abefd53d9697375d5",
    "isAdmin": true
  },
  {
    "_id": "5e190af15f2306f25ccc3dcf",
    "name": "Ivory Mitchell",
    "profile_img":
      "https://s3.amazonaws.com/uifaces/faces/twitter/madysondesigns/128.jpg",
    "email": "Rachael35@hotmail.com",
    "business_id": "5e17d52abefd53d9697375d5",
    "isAdmin": false
  },
  {
    "_id": "5e190afb3e57e9a30a5bab62",
    "name": "Giles Johnson",
    "profile_img":
      "https://s3.amazonaws.com/uifaces/faces/twitter/alagoon/128.jpg",
    "email": "Eino.OKeefe72@hotmail.com",
    "business_id": "5e17d52abefd53d9697375d5",
    "isAdmin": false
  },
  {
    "_id": "5e190b02e5772f475367dda5",
    "name": "Miss Minerva Mante",
    "profile_img":
      "https://s3.amazonaws.com/uifaces/faces/twitter/leehambley/128.jpg",
    "email": "Henriette_Parisian@hotmail.com",
    "business_id": "5e17d52abefd53d9697375d5",
    "isAdmin": false
  }
  ]
}

### DELETE BUSINESS
DELETE {{baseurl}}/businesses/{{business_id}}


###### Authentication Requests

### AUTH REGISTER

POST {{baseurl}}/auth/register
Content-Type: {{contentType}}

{
  "name": "Tester Account",
  "username": "TestAccount",
  "email":"testaccount@mail.com",
  "password": "testaccount"
}

### AUTH VERIFY ACCOUNT
# Take user id and token id from above request

# These will change
@userId = 5e1e4c2ad339981ea3ac040b
@tokenId=5e1e4c2ad339981ea3ac040c
PUT {{baseurl}}/auth/verify/user/{{userId}}/token/{{tokenId}}

### AUTH LOGIN 
# This request will should not pass without verifying account

POST {{baseurl}}/auth/login
Content-Type: {{contentType}}

{
  "username": "TestAccount",
  "password": "testaccount"
}